' <auto-generated />
Imports Microsoft.EntityFrameworkCore
Imports Microsoft.EntityFrameworkCore.Infrastructure
Imports Microsoft.EntityFrameworkCore.Metadata
Imports Microsoft.EntityFrameworkCore.Migrations
Imports Microsoft.VisualBasic
Imports Mirage.Core.Database.DbContexts

Namespace Global.Mirage.Core.Database.Migrations
    <DbContext(GetType(MirageDbContext))>
    <Migration("20240410095655_MergeExistingMigrations")>
    Partial Class MergeExistingMigrations
        ''' <inheritdoc />
        Protected Overrides Sub BuildTargetModel(modelBuilder As ModelBuilder)
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3")

            modelBuilder.Entity("Mirage.Core.Database.Types.Account",
                Sub(b)
                    b.Property(Of Integer)("AccountId").
                        ValueGeneratedOnAdd().
                        HasColumnType("INTEGER")

                    b.Property(Of Integer)("Banned").
                        HasColumnType("INTEGER")

                    b.Property(Of String)("Login").
                        HasColumnType("TEXT")

                    b.Property(Of String)("Password").
                        HasColumnType("TEXT")

                    b.HasKey("AccountId")

                    b.ToTable("mirage_worlds_accounts", DirectCast(Nothing, String))
                End Sub)

            modelBuilder.Entity("Mirage.Core.Database.Types.Character",
                Sub(b)
                    b.Property(Of Integer)("CharacterId").
                        ValueGeneratedOnAdd().
                        HasColumnType("INTEGER")

                    b.Property(Of Integer)("AccountId").
                        HasColumnType("INTEGER")

                    b.Property(Of Integer)("JobId").
                        HasColumnType("INTEGER")

                    b.Property(Of String)("Name").
                        HasColumnType("TEXT")

                    b.Property(Of Byte)("Sex").
                        HasColumnType("INTEGER")

                    b.Property(Of Integer)("SpriteId").
                        HasColumnType("INTEGER")

                    b.HasKey("CharacterId")

                    b.ToTable("mirage_worlds_characters", DirectCast(Nothing, String))
                End Sub)

            modelBuilder.Entity("Mirage.Core.Database.Types.Character",
                Sub(b)

                    b.OwnsOne("Mirage.Core.Database.Types.Components.Leveling", "Level",
                        Sub(b1)
                            b1.Property(Of Integer)("CharacterId").
                                HasColumnType("INTEGER")

                            b1.Property(Of Integer)("Experience").
                                HasColumnType("INTEGER")

                            b1.Property(Of Integer)("Level").
                                HasColumnType("INTEGER")

                            b1.HasKey("CharacterId")

                            b1.ToTable("mirage_worlds_characters")
                            b1.WithOwner().
                                HasForeignKey("CharacterId")
                        End Sub)

                    b.OwnsOne("Mirage.Core.Database.Types.Components.Location", "Location",
                        Sub(b1)
                            b1.Property(Of Integer)("CharacterId").
                                HasColumnType("INTEGER")

                            b1.Property(Of Byte)("Direction").
                                HasColumnType("INTEGER")

                            b1.Property(Of Integer)("Map").
                                HasColumnType("INTEGER")

                            b1.Property(Of Byte)("X").
                                HasColumnType("INTEGER")

                            b1.Property(Of Byte)("Y").
                                HasColumnType("INTEGER")

                            b1.HasKey("CharacterId")

                            b1.ToTable("mirage_worlds_characters")
                            b1.WithOwner().
                                HasForeignKey("CharacterId")
                        End Sub)

                    b.OwnsOne("Mirage.Core.Database.Types.Components.Vitals", "Vitals",
                        Sub(b1)
                            b1.Property(Of Integer)("CharacterId").
                                HasColumnType("INTEGER")

                            b1.Property(Of Integer)("Health").
                                HasColumnType("INTEGER")

                            b1.Property(Of Integer)("Mana").
                                HasColumnType("INTEGER")

                            b1.Property(Of Integer)("Stamina").
                                HasColumnType("INTEGER")

                            b1.HasKey("CharacterId")

                            b1.ToTable("mirage_worlds_characters")
                            b1.WithOwner().
                                HasForeignKey("CharacterId")
                        End Sub)
                    b.Navigation("Level")

                    b.Navigation("Location")

                    b.Navigation("Vitals")
                End Sub)
        End Sub
    End Class
End Namespace
