' <auto-generated />
Imports Microsoft.EntityFrameworkCore
Imports Microsoft.EntityFrameworkCore.Infrastructure
Imports Microsoft.EntityFrameworkCore.Metadata
Imports Microsoft.EntityFrameworkCore.Migrations
Imports Microsoft.VisualBasic
Imports Mirage.Core.Database.DbContexts

Namespace Global.Mirage.Core.Database.Migrations
    <DbContext(GetType(MirageDbContext))>
    <Migration("20240314024120_InitialCreate")>
    Partial Class InitialCreate
        ''' <inheritdoc />
        Protected Overrides Sub BuildTargetModel(modelBuilder As ModelBuilder)
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3")
        End Sub
    End Class
End Namespace
