
namespace Core
{
    public class Packets
    {

        // Packets sent by client to server
        public enum ClientPackets
        {
            CLogin,
            CRegister,
            CAddChar,
            CUseChar,
            CDelChar,
            CSayMsg,
            CBroadcastMsg,
            CPlayerMsg,
            CAdminMsg,
            CPlayerMove,
            CPlayerDir,
            CUseItem,
            CAttack,
            CPlayerInfoRequest,
            CWarpMeTo,
            CWarpToMe,
            CWarpTo,
            CSetSprite,
            CGetStats,
            CRequestNewMap,
            CNeedMap,
            CMapGetItem,
            CMapDropItem,
            CKickPlayer,
            CBanList,
            CBanDestroy,
            CBanPlayer,
            CRequestEditMap,

            CSetAccess,
            CWhosOnline,
            CSetMotd,
            CSearch,
            CSkills,
            CCast,
            CSwapInvSlots,
            CSwapSkillSlots,

            CCheckPing,
            CUnequip,
            CRequestPlayerData,
            CRequestItem,
            CRequestNpc,
            CRequestResource,
            CSpawnItem,
            CTrainStat,

            CRequestAnimation,
            CRequestSkill,
            CRequestShop,
            CRequestLevelUp,
            CForgetSkill,
            CCloseShop,
            CBuyItem,
            CSellItem,
            CChangeBankSlots,
            CDepositItem,
            CWithdrawItem,
            CCloseBank,
            CAdminWarp,
            CTradeInvite,
            CHandleTradeInvite,
            CAcceptTrade,
            CDeclineTrade,
            CTradeItem,
            CUntradeItem,
            CAdmin,
            CSetHotbarSlot,
            CDeleteHotbarSlot,
            CUseHotbarSlot,
            CEventChatReply,
            CEvent,
            CSwitchesAndVariables,
            CRequestSwitchesAndVariables,

            CRequestProjectile,
            CClearProjectile,
            CEmote,
            CRequestParty,
            CAcceptParty,
            CDeclineParty,
            CLeaveParty,
            CPartyChatMsg,
            CRequestPets,
            CRequestPet,

            // *************************
            // ***   EDITOR PACKETS  ***
            // *************************
            CMapRespawn,
            CMapReport,
            CSaveMap,
            CSkillLearn,

            // ####################
            // ### Dev+ Packets ###
            // ####################
            CRequestEditAnimation,
            CSaveAnimation,
            CRequestEditJob,
            CSaveJob,
            CRequestEditItem,
            CSaveItem,
            CRequestEditNpc,
            CSaveNpc,
            CRequestEditPet,
            CSavePet,
            CRequestEditProjectile,
            CSaveProjectile,
            CRequestEditResource,
            CSaveResource,
            CRequestEditShop,
            CSaveShop,
            CRequestEditSkill,
            CSaveSkill,

            CRequestMoral,
            CSaveMoral,
            CRequestEditMoral,

            CSaveScript,
            CRequestEditScript,

            CCloseEditor,

            // Make sure COUNT is below everything else
            Count
        }

        // Packets sent by server to client
        public enum ServerPackets
        {
            SAes,
            SAlertMsg,
            SLoginOK,
            SPlayerChars,
            SJobData,
            SInGame,
            SPlayerInv,
            SPlayerInvUpdate,
            SPlayerWornEq,
            SPlayerHP,
            SPlayerSP,
            SPlayerStats,
            SPlayerData,
            SPlayerMove,
            SNpcMove,
            SPlayerDir,
            SPlayerXYOffset,
            SNpcDir,
            SPlayerXY,
            SAttack,
            SNpcAttack,
            SCheckForMap,
            SMapData,
            SMapItemData,
            SMapNpcData,
            SMapNpcUpdate,
            SGlobalMsg,
            SAdminMsg,
            SPlayerMsg,
            SMapMsg,
            SSpawnItem,
            SItemEditor,
            SUpdateItem,
            SSpawnNpc,
            SNpcDead,
            SNpcEditor,
            SUpdateNpc,
            SEditMap,
            SShopEditor,
            SUpdateShop,
            SSkillEditor,
            SUpdateSkill,
            SSkills,
            SLeftMap,
            SMapResource,
            SResourceEditor,
            SUpdateResource,
            SSendPing,
            SActionMsg,
            SPlayerEXP,
            SBlood,
            SAnimationEditor,
            SUpdateAnimation,
            SAnimation,
            SMapNpcVitals,
            SCooldown,
            SClearSkillBuffer,
            SSayMsg,
            SOpenShop,
            SResetShopAction,
            SStunned,
            SMapWornEq,
            SBank,
            SLeftGame,
            STradeInvite,
            STrade,
            SCloseTrade,
            STradeUpdate,
            STradeStatus,
            SMapReport,
            STarget,
            SAdmin,
            SMapNames,
            SCritical,
            SrClick,
            SHotbar,
            SSpawnEvent,
            SEventMove,
            SEventDir,
            SEventChat,
            SEventStart,
            SEventEnd,
            SPlayBGM,
            SPlaySound,
            SFadeoutBGM,
            SStopSound,
            SSwitchesAndVariables,
            SMapEventData,
            SChatBubble,
            SSpecialEffect,
            SPic,
            SHoldPlayer,
            SProjectileEditor,
            SUpdateProjectile,
            SMapProjectile,
            SJobEditor,
            SUpdateJob,
            SUpdateMoral,
            SEmote,
            SPartyInvite,
            SPartyUpdate,
            SUpdatePet,
            SPartyVitals,
            SPetEditor,
            SMoralEditor,

            STime,
            SClock,

            SScriptEditor,

            // Make sure COUNT is below everything else
            COUNT
        }

    }
}