'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System

Namespace My
    Friend Class MySettings
        Friend Function [Default]() As MySettings
            Throw New NotImplementedException()
        End Function
    End Class
End Namespace
