' <auto-generated />
Imports Microsoft.EntityFrameworkCore
Imports Microsoft.EntityFrameworkCore.Infrastructure
Imports Microsoft.EntityFrameworkCore.Metadata
Imports Microsoft.EntityFrameworkCore.Migrations
Imports Microsoft.VisualBasic
Imports Mirage.Core.Database.DbContexts

Namespace Global.Mirage.Core.Database.Migrations
    <DbContext(GetType(MirageDbContext))>
    <Migration("20240327000805_AddAccountsTable")>
    Partial Class AddAccountsTable
        ''' <inheritdoc />
        Protected Overrides Sub BuildTargetModel(modelBuilder As ModelBuilder)
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3")

            modelBuilder.Entity("Mirage.Core.Database.Types.Account",
                Sub(b)
                    b.Property(Of String)("Login").
                        HasColumnType("TEXT")

                    b.Property(Of Boolean)("Banned").
                        HasColumnType("INTEGER")

                    b.Property(Of String)("Password").
                        HasColumnType("TEXT")

                    b.HasKey("Login")

                    b.ToTable("Accounts")
                End Sub)

            modelBuilder.Entity("Mirage.Core.Database.Types.Character",
                Sub(b)
                    b.Property(Of String)("Name").
                        HasColumnType("TEXT")

                    b.HasKey("Name")

                    b.ToTable("Characters")
                End Sub)
        End Sub
    End Class
End Namespace
