on:
  pull_request:
    types:
      - closed

jobs:
  build-windows:
      name: Build for Windows
      runs-on: windows-latest
      steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive