name: Linux Build

on:
  push:
    branches: [ unix ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore and Build
        run: dotnet publish Source/Client/Client.csproj -c Release -r linux-x64
