jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Build project
        run: dotnet publish Source/Client/Client.csproj -c Release -r win-x64
